services:
  db:
    image: postgres:15
    container_name: sms_edge_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 20

  adminer:
    image: adminer:4
    container_name: sms_edge_adminer
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ADMINER_DEFAULT_SERVER=db
    ports:
      - "8080:8080"

  api:
    build: ./api
    container_name: sms_edge_api
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - API_PORT=${API_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - "8081:8081"

volumes:
  pgdata:
